# Generated by Django 3.0.3 on 2020-02-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
