# Generated by Django 3.0.3 on 2020-02-27 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200227_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
