# Generated by Django 3.0.3 on 2020-02-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
