# Generated by Django 3.0.3 on 2020-02-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200228_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course',
            new_name='comment',
        ),
    ]
