# Generated by Django 3.0.3 on 2020-03-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200228_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ManyToManyField(to='users.Course'),
        ),
    ]
