# Generated by Django 3.0.3 on 2020-03-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_comment_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='course',
        ),
    ]
