# Generated by Django 3.0.3 on 2020-03-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
