# Generated by Django 3.0.3 on 2020-03-04 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
