# Generated by Django 3.0.3 on 2020-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_course_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
